services:
  finance-service:
    image: ghcr.io/salvemundi/v7-finance:${IMAGE_TAG:-latest}
    ports:
      - "3001:3001"
    environment:
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
      - MOLLIE_API_KEY=${MOLLIE_API_KEY}
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@v7-core-db:5432/${DB_NAME}
      - DIRECTUS_STATIC_TOKEN=${DIRECTUS_STATIC_TOKEN}
      - INTERNAL_DIRECTUS_URL=${INTERNAL_DIRECTUS_URL}
      - NEXT_APP_INTERNAL_URL=${NEXT_APP_INTERNAL_URL}

  sync-service:
    image: ghcr.io/salvemundi/v7-sync:${IMAGE_TAG:-latest}
    ports:
      - "3002:3002"
    environment:
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
      - AZURE_TENANT_ID=${AZURE_WEBSITEV7_TENANT_ID}
      - AZURE_SYNC_CLIENT_ID=${AZURE_WEBSITEV7_SYNC_CLIENT_ID}
      - AZURE_SYNC_CLIENT_SECRET=${AZURE_WEBSITEV7_SYNC_CLIENT_SECRET}
      - DIRECTUS_STATIC_TOKEN=${DIRECTUS_STATIC_TOKEN}
      - INTERNAL_DIRECTUS_URL=${INTERNAL_DIRECTUS_URL}
      - NEXT_APP_INTERNAL_URL=${NEXT_APP_INTERNAL_URL}

  mail-service:
    image: ghcr.io/salvemundi/v7-mail:${IMAGE_TAG:-latest}
    ports:
      - "3003:3003"
    environment:
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
      - AZURE_MAIL_CLIENT_ID=${AZURE_WEBSITEV7_MAIL_CLIENT_ID}
      - AZURE_MAIL_CLIENT_SECRET=${AZURE_WEBSITEV7_MAIL_CLIENT_SECRET}
      - AZURE_WEBSITEV7_TENANT_ID=${AZURE_WEBSITEV7_TENANT_ID}
      - AZURE_MAIL_SENDER=${AZURE_MAIL_SENDER}
      - DIRECTUS_STATIC_TOKEN=${DIRECTUS_STATIC_TOKEN}
      - INTERNAL_DIRECTUS_URL=${INTERNAL_DIRECTUS_URL}
      - NEXT_APP_INTERNAL_URL=${NEXT_APP_INTERNAL_URL}
      - REDIS_URL=redis://v7-core-redis:6379

  frontend:
    image: ghcr.io/salvemundi/v7-app:${IMAGE_TAG:-latest}
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3000}
      - INTERNAL_FINANCE_URL=http://finance-service:3001
      - INTERNAL_SYNC_URL=http://sync-service:3002
      - INTERNAL_MAIL_URL=http://mail-service:3003
      - INTERNAL_DIRECTUS_URL=${INTERNAL_DIRECTUS_URL}
      - DIRECTUS_STATIC_TOKEN=${DIRECTUS_STATIC_TOKEN}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - AZURE_WEBSITEV7_TENANT_ID=${AZURE_WEBSITEV7_TENANT_ID}
      - AZURE_WEBSITEV7_AUTH_CLIENT_ID=${AZURE_WEBSITEV7_AUTH_CLIENT_ID}
      - AZURE_WEBSITEV7_AUTH_CLIENT_SECRET=${AZURE_WEBSITEV7_AUTH_CLIENT_SECRET}
      - AZURE_WEBSITEV7_DIRECTUS_CLIENT_ID=${AZURE_WEBSITEV7_DIRECTUS_CLIENT_ID}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - PUBLIC_URL=${PUBLIC_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - INTERNAL_DB_HOST=${INTERNAL_DB_HOST}
      - HOSTNAME=0.0.0.0
    networks:
      - default
      - proxy-network
    depends_on:
      - finance-service

networks:
  default:
    name: salve-mundi-v7-shared
    external: true
  proxy-network:
    external: true
