/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is generated by scripts/generate-zod.ts based on the Drizzle schema.
 * Run `pnpm generate:zod` to update this file.
 */

import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import * as schema from '@salvemundi/db/schema';

// --- club_members ---
export const insertClubMembersSchema = createInsertSchema(schema.club_members);
export const selectClubMembersSchema = createSelectSchema(schema.club_members);

// --- Stickers ---
export const insertStickersSchema = createInsertSchema(schema.Stickers);
export const selectStickersSchema = createSelectSchema(schema.Stickers);

// --- Board ---
export const insertBoardSchema = createInsertSchema(schema.Board);
export const selectBoardSchema = createSelectSchema(schema.Board);

// --- Board_Members ---
export const insertBoardMembersSchema = createInsertSchema(schema.Board_Members);
export const selectBoardMembersSchema = createSelectSchema(schema.Board_Members);

// --- contacts ---
export const insertContactsSchema = createInsertSchema(schema.contacts);
export const selectContactsSchema = createSelectSchema(schema.contacts);

// --- directus_access ---
export const insertDirectusAccessSchema = createInsertSchema(schema.directus_access);
export const selectDirectusAccessSchema = createSelectSchema(schema.directus_access);

// --- committees ---
export const insertCommitteesSchema = createInsertSchema(schema.committees);
export const selectCommitteesSchema = createSelectSchema(schema.committees);

// --- directus_comments ---
export const insertDirectusCommentsSchema = createInsertSchema(schema.directus_comments);
export const selectDirectusCommentsSchema = createSelectSchema(schema.directus_comments);

// --- directus_dashboards ---
export const insertDirectusDashboardsSchema = createInsertSchema(schema.directus_dashboards);
export const selectDirectusDashboardsSchema = createSelectSchema(schema.directus_dashboards);

// --- directus_folders ---
export const insertDirectusFoldersSchema = createInsertSchema(schema.directus_folders);
export const selectDirectusFoldersSchema = createSelectSchema(schema.directus_folders);

// --- directus_extensions ---
export const insertDirectusExtensionsSchema = createInsertSchema(schema.directus_extensions);
export const selectDirectusExtensionsSchema = createSelectSchema(schema.directus_extensions);

// --- directus_fields ---
export const insertDirectusFieldsSchema = createInsertSchema(schema.directus_fields);
export const selectDirectusFieldsSchema = createSelectSchema(schema.directus_fields);

// --- coupons ---
export const insertCouponsSchema = createInsertSchema(schema.coupons);
export const selectCouponsSchema = createSelectSchema(schema.coupons);

// --- directus_activity ---
export const insertDirectusActivitySchema = createInsertSchema(schema.directus_activity);
export const selectDirectusActivitySchema = createSelectSchema(schema.directus_activity);

// --- directus_migrations ---
export const insertDirectusMigrationsSchema = createInsertSchema(schema.directus_migrations);
export const selectDirectusMigrationsSchema = createSelectSchema(schema.directus_migrations);

// --- directus_files ---
export const insertDirectusFilesSchema = createInsertSchema(schema.directus_files);
export const selectDirectusFilesSchema = createSelectSchema(schema.directus_files);

// --- directus_collections ---
export const insertDirectusCollectionsSchema = createInsertSchema(schema.directus_collections);
export const selectDirectusCollectionsSchema = createSelectSchema(schema.directus_collections);

// --- directus_flows ---
export const insertDirectusFlowsSchema = createInsertSchema(schema.directus_flows);
export const selectDirectusFlowsSchema = createSelectSchema(schema.directus_flows);

// --- directus_panels ---
export const insertDirectusPanelsSchema = createInsertSchema(schema.directus_panels);
export const selectDirectusPanelsSchema = createSelectSchema(schema.directus_panels);

// --- directus_permissions ---
export const insertDirectusPermissionsSchema = createInsertSchema(schema.directus_permissions);
export const selectDirectusPermissionsSchema = createSelectSchema(schema.directus_permissions);

// --- directus_presets ---
export const insertDirectusPresetsSchema = createInsertSchema(schema.directus_presets);
export const selectDirectusPresetsSchema = createSelectSchema(schema.directus_presets);

// --- directus_roles ---
export const insertDirectusRolesSchema = createInsertSchema(schema.directus_roles);
export const selectDirectusRolesSchema = createSelectSchema(schema.directus_roles);

// --- directus_revisions ---
export const insertDirectusRevisionsSchema = createInsertSchema(schema.directus_revisions);
export const selectDirectusRevisionsSchema = createSelectSchema(schema.directus_revisions);

// --- directus_relations ---
export const insertDirectusRelationsSchema = createInsertSchema(schema.directus_relations);
export const selectDirectusRelationsSchema = createSelectSchema(schema.directus_relations);

// --- directus_shares ---
export const insertDirectusSharesSchema = createInsertSchema(schema.directus_shares);
export const selectDirectusSharesSchema = createSelectSchema(schema.directus_shares);

// --- directus_notifications ---
export const insertDirectusNotificationsSchema = createInsertSchema(schema.directus_notifications);
export const selectDirectusNotificationsSchema = createSelectSchema(schema.directus_notifications);

// --- directus_policies ---
export const insertDirectusPoliciesSchema = createInsertSchema(schema.directus_policies);
export const selectDirectusPoliciesSchema = createSelectSchema(schema.directus_policies);

// --- directus_operations ---
export const insertDirectusOperationsSchema = createInsertSchema(schema.directus_operations);
export const selectDirectusOperationsSchema = createSelectSchema(schema.directus_operations);

// --- directus_translations ---
export const insertDirectusTranslationsSchema = createInsertSchema(schema.directus_translations);
export const selectDirectusTranslationsSchema = createSelectSchema(schema.directus_translations);

// --- directus_versions ---
export const insertDirectusVersionsSchema = createInsertSchema(schema.directus_versions);
export const selectDirectusVersionsSchema = createSelectSchema(schema.directus_versions);

// --- documents ---
export const insertDocumentsSchema = createInsertSchema(schema.documents);
export const selectDocumentsSchema = createSelectSchema(schema.documents);

// --- events ---
export const insertEventsSchema = createInsertSchema(schema.events);
export const selectEventsSchema = createSelectSchema(schema.events);

// --- event_signups ---
export const insertEventSignupsSchema = createInsertSchema(schema.event_signups);
export const selectEventSignupsSchema = createSelectSchema(schema.event_signups);

// --- events_directus_users ---
export const insertEventsDirectusUsersSchema = createInsertSchema(schema.events_directus_users);
export const selectEventsDirectusUsersSchema = createSelectSchema(schema.events_directus_users);

// --- hero_banners_files ---
export const insertHeroBannersFilesSchema = createInsertSchema(schema.hero_banners_files);
export const selectHeroBannersFilesSchema = createSelectSchema(schema.hero_banners_files);

// --- intro_blog_likes ---
export const insertIntroBlogLikesSchema = createInsertSchema(schema.intro_blog_likes);
export const selectIntroBlogLikesSchema = createSelectSchema(schema.intro_blog_likes);

// --- intro_blogs ---
export const insertIntroBlogsSchema = createInsertSchema(schema.intro_blogs);
export const selectIntroBlogsSchema = createSelectSchema(schema.intro_blogs);

// --- events_members ---
export const insertEventsMembersSchema = createInsertSchema(schema.events_members);
export const selectEventsMembersSchema = createSelectSchema(schema.events_members);

// --- hero_banners ---
export const insertHeroBannersSchema = createInsertSchema(schema.hero_banners);
export const selectHeroBannersSchema = createSelectSchema(schema.hero_banners);

// --- intro_blog_gallery ---
export const insertIntroBlogGallerySchema = createInsertSchema(schema.intro_blog_gallery);
export const selectIntroBlogGallerySchema = createSelectSchema(schema.intro_blog_gallery);

// --- pub_crawl_events ---
export const insertPubCrawlEventsSchema = createInsertSchema(schema.pub_crawl_events);
export const selectPubCrawlEventsSchema = createSelectSchema(schema.pub_crawl_events);

// --- membership_history ---
export const insertMembershipHistorySchema = createInsertSchema(schema.membership_history);
export const selectMembershipHistorySchema = createSelectSchema(schema.membership_history);

// --- jobs ---
export const insertJobsSchema = createInsertSchema(schema.jobs);
export const selectJobsSchema = createSelectSchema(schema.jobs);

// --- pub_crawl_signups_transactions ---
export const insertPubCrawlSignupsTransactionsSchema = createInsertSchema(schema.pub_crawl_signups_transactions);
export const selectPubCrawlSignupsTransactionsSchema = createSelectSchema(schema.pub_crawl_signups_transactions);

// --- push_notification ---
export const insertPushNotificationSchema = createInsertSchema(schema.push_notification);
export const selectPushNotificationSchema = createSelectSchema(schema.push_notification);

// --- permissions ---
export const insertPermissionsSchema = createInsertSchema(schema.permissions);
export const selectPermissionsSchema = createSelectSchema(schema.permissions);

// --- intro_signups ---
export const insertIntroSignupsSchema = createInsertSchema(schema.intro_signups);
export const selectIntroSignupsSchema = createSelectSchema(schema.intro_signups);

// --- pub_crawl_signups ---
export const insertPubCrawlSignupsSchema = createInsertSchema(schema.pub_crawl_signups);
export const selectPubCrawlSignupsSchema = createSelectSchema(schema.pub_crawl_signups);

// --- intro_planning ---
export const insertIntroPlanningSchema = createInsertSchema(schema.intro_planning);
export const selectIntroPlanningSchema = createSelectSchema(schema.intro_planning);

// --- pub_crawl_tickets ---
export const insertPubCrawlTicketsSchema = createInsertSchema(schema.pub_crawl_tickets);
export const selectPubCrawlTicketsSchema = createSelectSchema(schema.pub_crawl_tickets);

// --- roles ---
export const insertRolesSchema = createInsertSchema(schema.roles);
export const selectRolesSchema = createSelectSchema(schema.roles);

// --- intro_parent_signups ---
export const insertIntroParentSignupsSchema = createInsertSchema(schema.intro_parent_signups);
export const selectIntroParentSignupsSchema = createSelectSchema(schema.intro_parent_signups);

// --- whatsapp_groups ---
export const insertWhatsappGroupsSchema = createInsertSchema(schema.whatsapp_groups);
export const selectWhatsappGroupsSchema = createSelectSchema(schema.whatsapp_groups);

// --- trips ---
export const insertTripsSchema = createInsertSchema(schema.trips);
export const selectTripsSchema = createSelectSchema(schema.trips);

// --- trip_signups ---
export const insertTripSignupsSchema = createInsertSchema(schema.trip_signups);
export const selectTripSignupsSchema = createSelectSchema(schema.trip_signups);

// --- trip_activities ---
export const insertTripActivitiesSchema = createInsertSchema(schema.trip_activities);
export const selectTripActivitiesSchema = createSelectSchema(schema.trip_activities);

// --- trip_signup_activities ---
export const insertTripSignupActivitiesSchema = createInsertSchema(schema.trip_signup_activities);
export const selectTripSignupActivitiesSchema = createSelectSchema(schema.trip_signup_activities);

// --- safe_havens ---
export const insertSafeHavensSchema = createInsertSchema(schema.safe_havens);
export const selectSafeHavensSchema = createSelectSchema(schema.safe_havens);

// --- sponsors ---
export const insertSponsorsSchema = createInsertSchema(schema.sponsors);
export const selectSponsorsSchema = createSelectSchema(schema.sponsors);

// --- system_logs ---
export const insertSystemLogsSchema = createInsertSchema(schema.system_logs);
export const selectSystemLogsSchema = createSelectSchema(schema.system_logs);

// --- clubs ---
export const insertClubsSchema = createInsertSchema(schema.clubs);
export const selectClubsSchema = createSelectSchema(schema.clubs);

// --- directus_sessions ---
export const insertDirectusSessionsSchema = createInsertSchema(schema.directus_sessions);
export const selectDirectusSessionsSchema = createSelectSchema(schema.directus_sessions);

// --- role_permissions ---
export const insertRolePermissionsSchema = createInsertSchema(schema.role_permissions);
export const selectRolePermissionsSchema = createSelectSchema(schema.role_permissions);

// --- auth_accounts ---
export const insertAuthAccountsSchema = createInsertSchema(schema.auth_accounts);
export const selectAuthAccountsSchema = createSelectSchema(schema.auth_accounts);

// --- auth_sessions ---
export const insertAuthSessionsSchema = createInsertSchema(schema.auth_sessions);
export const selectAuthSessionsSchema = createSelectSchema(schema.auth_sessions);

// --- verification ---
export const insertVerificationSchema = createInsertSchema(schema.verification);
export const selectVerificationSchema = createSelectSchema(schema.verification);

// --- committee_members ---
export const insertCommitteeMembersSchema = createInsertSchema(schema.committee_members);
export const selectCommitteeMembersSchema = createSelectSchema(schema.committee_members);

// --- feature_flags ---
export const insertFeatureFlagsSchema = createInsertSchema(schema.feature_flags);
export const selectFeatureFlagsSchema = createSelectSchema(schema.feature_flags);

// --- transactions ---
export const insertTransactionsSchema = createInsertSchema(schema.transactions);
export const selectTransactionsSchema = createSelectSchema(schema.transactions);

// --- intro_planning_signups ---
export const insertIntroPlanningSignupsSchema = createInsertSchema(schema.intro_planning_signups);
export const selectIntroPlanningSignupsSchema = createSelectSchema(schema.intro_planning_signups);

// --- directus_users ---
export const insertDirectusUsersSchema = createInsertSchema(schema.directus_users);
export const selectDirectusUsersSchema = createSelectSchema(schema.directus_users);

// --- directus_deployments ---
export const insertDirectusDeploymentsSchema = createInsertSchema(schema.directus_deployments);
export const selectDirectusDeploymentsSchema = createSelectSchema(schema.directus_deployments);

// --- directus_deployment_projects ---
export const insertDirectusDeploymentProjectsSchema = createInsertSchema(schema.directus_deployment_projects);
export const selectDirectusDeploymentProjectsSchema = createSelectSchema(schema.directus_deployment_projects);

// --- directus_settings ---
export const insertDirectusSettingsSchema = createInsertSchema(schema.directus_settings);
export const selectDirectusSettingsSchema = createSelectSchema(schema.directus_settings);

// --- directus_deployment_runs ---
export const insertDirectusDeploymentRunsSchema = createInsertSchema(schema.directus_deployment_runs);
export const selectDirectusDeploymentRunsSchema = createSelectSchema(schema.directus_deployment_runs);

// --- webshop_drop_windows ---
export const insertWebshopDropWindowsSchema = createInsertSchema(schema.webshop_drop_windows);
export const selectWebshopDropWindowsSchema = createSelectSchema(schema.webshop_drop_windows);

// --- webshop_products ---
export const insertWebshopProductsSchema = createInsertSchema(schema.webshop_products);
export const selectWebshopProductsSchema = createSelectSchema(schema.webshop_products);

// --- webshop_product_media ---
export const insertWebshopProductMediaSchema = createInsertSchema(schema.webshop_product_media);
export const selectWebshopProductMediaSchema = createSelectSchema(schema.webshop_product_media);

// --- webshop_product_variants ---
export const insertWebshopProductVariantsSchema = createInsertSchema(schema.webshop_product_variants);
export const selectWebshopProductVariantsSchema = createSelectSchema(schema.webshop_product_variants);

// --- webshop_preorders ---
export const insertWebshopPreordersSchema = createInsertSchema(schema.webshop_preorders);
export const selectWebshopPreordersSchema = createSelectSchema(schema.webshop_preorders);

// --- webshop_preorder_lines ---
export const insertWebshopPreorderLinesSchema = createInsertSchema(schema.webshop_preorder_lines);
export const selectWebshopPreorderLinesSchema = createSelectSchema(schema.webshop_preorder_lines);

