export const ROUTES = {
    HOME: '/',
    INTRO: '/intro',
    MEMBERSHIP: '/lidmaatschap',
    ACTIVITIES: '/activiteiten',
    COMMITTEES: '/commissies',
    CLUBS: '/clubs',
    CONTACT: '/contact',
    SAFE_HAVENS: '/safe-havens',
    PUB_CRAWL: '/kroegentocht',
    TRIP: '/reis',
    STICKERS: '/stickers',
    ACCOUNT: '/account',
    SIGNUP: '/signup',
    TRANSACTIONS: '/transacties',
    WHATSAPP_GROUPS: '/whatsapp-groepen',
    ATTENDANCE: '/aanwezigheid',
    ADMIN: '/admin',
} as const;
